// Prompts and affirmations for the daily journaling app.
// Prompts are intentionally gentle and never ask for graphic recall.
const PROMPTS = [
  "What's one thing your body needed today that it didn't get?",
  "Name a moment today when you felt even a little bit safe.",
  "What would you say to comfort a friend who felt the way you feel right now?",
  "What's something small you did today that took more courage than it looked like?",
  "If today had a weather forecast, what would it be — and is that okay?",
  "What's one thing you're proud of getting through, even if no one else noticed?",
  "Where in your body are you holding tension right now? What might it need?",
  "What's a kind thing someone could say to you today that you'd actually believe?",
  "What helped you feel even slightly grounded today?",
  "What's one boundary you wish you could set, for yourself or with someone else?",
  "What does 'rest' look like for you this week?",
  "What's something you're carrying that you don't have to carry alone?",
  "If your younger self could see you now, what would you want them to know?",
  "What's one thing that felt heavy today, and what's one thing that felt light?",
  "What do you need to hear right now, even if you can't say it out loud yet?",
  "What's a small act of care you can offer yourself before this day ends?",
  "What's something you survived that you don't give yourself enough credit for?",
  "Is there a feeling today that you haven't let yourself fully feel? You can name it here.",
  "What's one thing that made today even a little easier?",
  "What would 'enough' look like for you today?",
  "What's a memory that brings you a little warmth, even briefly?",
  "What part of you needs the most gentleness today?",
  "What's something you wish someone had told you a long time ago?",
  "How did you take care of yourself today, even in a small way?",
  "What's one thing you're allowed to let go of, just for tonight?",
];

const AFFIRMATIONS = [
  "You showed up for yourself today, and that matters.",
  "Your feelings are valid, even the ones that don't make sense yet.",
  "Healing isn't a straight line, and you're still moving.",
  "You don't have to carry everything alone.",
  "It's okay to take up space with your story.",
  "You are allowed to rest without earning it.",
  "What happened to you does not define your worth.",
  "Small steps still count as moving forward.",
  "You are safe enough, right here, right now.",
  "Your pace is the right pace.",
  "Being gentle with yourself is not a weakness.",
  "You are more than what you've been through.",
  "It's okay to not be okay today.",
  "You get to decide what healing looks like for you.",
  "You are doing better than you think you are.",
  "There is nothing wrong with needing time.",
  "You deserve the same kindness you give to others.",
  "Your story isn't over — you're still writing it.",
];
